### ISSUE TITLE
have a bug ?

### ISSUE THREAD

**Issue by liquehuo** [mucahiddanis/Abp.AspNetCore.Mvc.UI.Theme.AdminLTE#4]
In 'Personal info' page ,I clicked the submit button and reported an error！

**Manage.cshtml**
**@foreach (var group in Model.ProfileManagementPageCreationContext.Groups)**

Model.ProfileManagementPageCreationContext is null .

Hope to check and look forward to reply ， thanks！！

**Comment by mucahiddanis** [comment]
[bug fixed with this commit](https://github.com/mucahiddanis/Abp.AspNetCore.Mvc.UI.Theme.AdminLTE/commit/5597e2c77e7062a489aa3c0d89bf61f2750c8e0d)

**Comment by mucahiddanis** [comment]
![image](https://user-images.githubusercontent.com/16820194/96149011-824ee000-0f11-11eb-9c37-4ecf80065391.png)

**Comment by liquehuo** [comment]
where are you come from? Chinese people ?
